### ISSUE TITLE
Swift Potentially Uses the Wrong Swift Driver

### ISSUE THREAD

**Issue by thekief** [apple/swift-driver#1349]
I recently opened an issue on the Swift repo (https://github.com/apple/swift/issues/65461) but realised after some debugging that it probabl better fits here.

When trying to build an existing application with a custom toolchain based on the Swift 5.8 Release (https://github.com/apple/swift/commit/f9611bc8e745b1b9a98d494236adb6d6c739fe97) the application will not compile due to the Swift Package Manager trying to disallow the new driver.

I noticed that when executing `swiftc -version` the output seems to vastly differ. With Xcode's **swiftc** I get following output:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -version
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
```

while with the custom compiler I get following output:

```
/Library/Developer/Toolchains/swift-LOCAL-2023-05-02-a.xctoolchain/usr/bin/swift-frontend -version
Apple Swift version 5.8 (swift-5.8-RELEASE)
Target: arm64-apple-macosx13.0
```

To me it looks like there are some issues with the custom compiled toolchain choosing the wrong driver. Is there any easy-fix for this?

**Comment by thekief** [comment]
Sorry, my bad. I put the wrong command there. Here is the corrected one:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -version
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
```

Anyway, my problem still applied. I did some debugging with `dtruss` and noticed that the my custom toolchain does not check for `swift-driver` while the stock one does:

```
351- 1234/0x252e:     16496       1      0 sysctl([CTL_KERN, 4, 0, 0, 0, 0] (2), 0x16BC19140, 0x16BC18DA0, 0x0, 0x0)		 = 0 0
352- 1234/0x252e:     16500       4      3 sysctl([CTL_HW, 1, 0, 0, 0, 0] (2), 0x16BC19240, 0x16BC18DA0, 0x0, 0x0)		 = 0 0
353: 1234/0x252e:     16505       3      2 access("/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver\0", 0x0, 0x0)		 = 0 0
354: 1234/0x252e:     16507       2      1 access("/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver\0", 0x0, 0x0)		 = 0 0
355- 1234/0x2530:     17970:        0:       0 fork()		 = 0 0
356- 1234/0x2530:     17971       1      0 mprotect(0x104EB4000, 0x8000, 0x1)	
```

 I also noticed this details in the README:

https://github.com/apple/swift-driver/blob/main/README.md?plain=1#L14

Previous snapshots of Swift worked without any problems in that regard. Could it be that using a self-built "release" disables forwarding executions to the driver?

**Comment by artemcm** [comment]
Could you please clarify how your build a custom toolchain, exactly?

**Comment by thekief** [comment]
I used the official instructions aka:

`swift/utils/build-toolchain <prefix>`

**Comment by artemcm** [comment]
> I used the official instructions aka:
> 
> `swift/utils/build-toolchain <prefix>`

Could you please share which `<prefix>` you are using?

**Comment by thekief** [comment]
Sure, sorry for leaving out this details. My bundle prefix is `customCompiler`.

Is there anything special you have in mind? Are there some names that are considered "forbidden"?

**Comment by artemcm** [comment]
@thekief do you have a `swift-driver` executable adjacent to `/Library/Developer/Toolchains/swift-LOCAL-2023-05-02-a.xctoolchain/usr/bin/swiftc`? 

I am having trouble using `build-toolchain` script locally, but I just triggered a toolchain build on a `release/5.8` PR here:
https://github.com/apple/swift/pull/65587

And the resulting [toolchain](https://ci.swift.org/job/swift-PR-toolchain-macos/672/artifact/branch-release/5.8/swift-PR-65587-672-osx.tar.gz) seems to have the new driver correctly installed and it does get used when calling `swiftc` from this toolchain.

**Comment by thekief** [comment]
Thank you for your help there. I had a look at your build and I noticed that some files on my side were kind of missing and broken most likely due to some issues in the build process. 

We had some issues during our build times in the night and so far restarting/resuming the build process never caused any issues. That is the first time for me here. I will test the toolchains internally and potentially close the ticket soon

**Comment by thekief** [comment]
i will inform you until next Monday. Currently, we switched back to Xcode 14, circumventing any problems with this. I will write about the outcome as soon as possible.

**Comment by MaxDesiatov** [comment]
@thekief have you had a chance to reproduce this again?

**Comment by thekief** [comment]
Related to this one here:

https://github.com/apple/swift-package-manager/issues/6970

I kinda forgot about this issue. Thank you for the reminder

**Comment by MaxDesiatov** [comment]
I don't think that SwiftPM issue is related in any way, unless some details in the description of this one were omitted.

**Comment by thekief** [comment]
Sorry for the bad phrasing: 

I wanted to retest it with the new version mentioned in the other ticket. As I cannot build the new version, I have no update on it yet.

**Comment by thekief** [comment]
I was able to build `release/5.9.0` and the issue does not occure anymore.
